name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close inactive
        uses: actions-cool/issues-helper@v1.11
        with:
          actions: 'close-issues'
          inactive-day: 90
          body: |
            It's inactive above 3 months, feel free to reopen if still have problems.
